version: '3.3'
services:
  orai:
    container_name: orai_node
    image: oraichain/foundation-orai:0.42.0-alpine-prod
    working_dir: /workspace
    tty: true
    restart: on-failure
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
      - 9090:9090
      - 8545:8545
    cap_add:
      - SYS_PTRACE
    env_file:
      - orai.env
    volumes:
      - ./:/workspace
      - oraivisor:/root/oraivisor

volumes:
  oraivisor:
